stages:
  - initialize
  - compile
  - test
  - package
  - release

cache:
  paths:
    - ".m2/repository/"

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"

initialize_JH:
  stage: initialize
  image: registry.jihulab.com/docker/hub/centos:centos7
  rules:
    - if: "$CI_SERVER_URL =~ /jihulab.com/"
  script:
    - sed -e 's|^mirrorlist=|#mirrorlist=|g' -e 's|^#baseurl=http://mirror.centos.org|baseurl=https://mirrors.tuna.tsinghua.edu.cn|g' -i.bak /etc/yum.repos.d/CentOS-*.repo
    - yum makecache
    - yum install -y wget unzip git
    - wget $CI_SERVER_URL/$CI_PROJECT_NAMESPACE/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.BIN.ZIP
    - wget $CI_SERVER_URL/$CI_PROJECT_NAMESPACE/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP
    - unzip -o IP2LOCATION-LITE-DB11.BIN.ZIP -d src/main/resources/ip2location/
    - unzip -o IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d src/main/resources/ip2location/
    - git clone https://renfei:$JH_TOKEN@jihulab.com/renfei/config.git
    - cp -rf ./config/renfeid/* ./src/main/resources/
  artifacts:
    expire_in: 1d
    when: on_success
    paths:
      - src/main/resources/ip2location/
      - src/main/resources/application-gitlab.yml
      - src/main/resources/application-prod.yml

initialize:
  stage: initialize
  image: centos:centos7
  rules:
    - if: "$CI_SERVER_URL =~ /gitlab.com/"
  script:
    - yum install -y wget unzip git
    - wget $CI_SERVER_URL/$CI_PROJECT_NAMESPACE/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.BIN.ZIP
    - wget $CI_SERVER_URL/$CI_PROJECT_NAMESPACE/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP
    - unzip -o IP2LOCATION-LITE-DB11.BIN.ZIP -d src/main/resources/ip2location/
    - unzip -o IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d src/main/resources/ip2location/
    - git clone https://cd-robot:$CD_ROBOT_TOKEN@github.com/renfei/config.git
    - cp -rf ./config/renfeid/* ./src/main/resources/
  artifacts:
    expire_in: 1d
    when: on_success
    paths:
      - src/main/resources/ip2location/
      - src/main/resources/application-gitlab.yml
      - src/main/resources/application-prod.yml

compile_JH:
  stage: compile
  image: registry.jihulab.com/docker/hub/maven:3.8.4-openjdk-8
  rules:
    - if: "$CI_SERVER_URL =~ /jihulab.com/"
  script:
    - cp -rf environment/maven/settings.xml /usr/share/maven/conf/settings.xml
    - mvn compile

compile:
  stage: compile
  image: maven:3.8.4-openjdk-8
  rules:
    - if: "$CI_SERVER_URL =~ /gitlab.com/"
  script:
    - mvn compile

test_JH:
  stage: test
  image: registry.jihulab.com/docker/hub/centos:centos7
  rules:
    - if: "$CI_SERVER_URL =~ /jihulab.com/"
  services:
    - name: registry.jihulab.com/docker/hub/mariadb:10.6.5
      alias: "mariadb"
    - name: registry.jihulab.com/docker/hub/redis:6.0.1
      alias: "redis"
    - name: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/elasticsearch:7.16.3"
      alias: "elasticsearch"
      command: [ "bin/elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node" ]
  variables:
    MARIADB_DATABASE: renfeid
    MARIADB_ROOT_PASSWORD: root
  before_script:
    - sed -e 's|^mirrorlist=|#mirrorlist=|g' -e 's|^#baseurl=http://mirror.centos.org|baseurl=https://mirrors.tuna.tsinghua.edu.cn|g' -i.bak /etc/yum.repos.d/CentOS-*.repo
    - yum makecache
    - yum install -y wget java-1.8.0-openjdk* which
    - curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
    - rpm --import https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    - yum install -y MariaDB-server galera-4 MariaDB-client MariaDB-shared MariaDB-backup MariaDB-common
    - mariadb --user=root --password="$MARIADB_ROOT_PASSWORD" --host=mariadb $MARIADB_DATABASE
      < environment/db/renfeid.sql --default-character-set=utf8
  script:
    - ./mvnw test -P gitlab -s environment/maven/settings.xml

test:
  stage: test
  image: centos:centos7
  rules:
    - if: "$CI_SERVER_URL =~ /gitlab.com/"
  services:
    - mariadb:10.6.5
    - redis:6.0.1
    - name: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/elasticsearch:7.16.3"
      alias: "elasticsearch"
      command: [ "bin/elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node" ]
  variables:
    MARIADB_DATABASE: renfeid
    MARIADB_ROOT_PASSWORD: root
  before_script:
    - yum install -y wget java-1.8.0-openjdk* which
    - curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
    - rpm --import https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    - yum install -y MariaDB-server galera-4 MariaDB-client MariaDB-shared MariaDB-backup MariaDB-common
    - mariadb --user=root --password="$MARIADB_ROOT_PASSWORD" --host=mariadb $MARIADB_DATABASE
      < environment/db/renfeid.sql --default-character-set=utf8
  script:
    - ./mvnw test -P gitlab

package_JH:
  stage: package
  image: registry.jihulab.com/docker/hub/maven:3.8.4-openjdk-8
  rules:
    - if: $CI_COMMIT_TAG && "$CI_SERVER_URL =~ /jihulab.com/"
  before_script:
    - rm -rf src/main/resources/ip2location
  script:
    - mvn clean package -Dmaven.test.skip=true -P prod
  artifacts:
    expire_in: 1d
    when: on_success
    paths:
      - target/

package:
  stage: package
  image: maven:3.8.4-openjdk-8
  rules:
    - if: $CI_COMMIT_TAG && "$CI_SERVER_URL =~ /gitlab.com/"
  before_script:
    - rm -rf src/main/resources/ip2location
  script:
    - mvn clean package -Dmaven.test.skip=true -P prod
  artifacts:
    expire_in: 1d
    when: on_success
    paths:
      - target/

release:
  stage: release
  image: docker:latest
  rules:
    - if: $CI_COMMIT_TAG
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  dependencies:
    - package
  environment:
    name: production
    url: https://www.renfei.net/