image: centos:centos7

stages:
  - initialize
  - compile
  - test
  - release

cache:
  paths:
    - ".m2/repository/"

initialize_environmen_jihu:
  stage: initialize
  script:
    - yum install -y wget unzip
    - wget https://jihulab.com/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.BIN.ZIP
    - wget https://jihulab.com/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP
    - unzip -o IP2LOCATION-LITE-DB11.BIN.ZIP -d src/main/resources/ip2location/
    - unzip -o IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d src/main/resources/ip2location/
  artifacts:
    expire_in: 1d
    when: on_success
    paths:
      - src/main/resources/ip2location/
  rules:
    - if: "$CI_SERVER_URL =~ /jihulab.com/"

initialize_environmen_gitlab:
  stage: initialize
  script:
    - yum install -y wget unzip
    - wget https://gitlab.com/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.BIN.ZIP
    - wget https://gitlab.com/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP
    - unzip -o IP2LOCATION-LITE-DB11.BIN.ZIP -d src/main/resources/ip2location/
    - unzip -o IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d src/main/resources/ip2location/
  artifacts:
    expire_in: 1d
    when: on_success
    paths:
      - src/main/resources/ip2location/
  rules:
    - if: "$CI_SERVER_URL =~ /gitlab.com/"

compile:
  stage: compile
  image: maven:3.8.4-openjdk-8
  script:
    - mvn --batch-mode compile
  artifacts:
    expire_in: 1d
    when: on_success
    paths:
      - src/main/resources/ip2location/

test_job_jh:
  stage: test
  image: centos:centos7
  rules:
    - if: "$CI_SERVER_URL =~ /jihulab.com/"
  services:
    - mariadb:10.6.5
    - redis:6.0.1
    - name: "registry.jihulab.com/renfei/elasticsearch:7.16.2"
      alias: "elasticsearch"
      command: [ "bin/elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node" ]
  variables:
    MARIADB_DATABASE: renfeid
    MARIADB_ROOT_PASSWORD: root
  before_script:
    - yum install -y wget java-1.8.0-openjdk* which git
    - curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
    - rpm --import https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    - yum install -y MariaDB-server galera-4 MariaDB-client MariaDB-shared MariaDB-backup MariaDB-common
    - mariadb --user=root --password="$MARIADB_ROOT_PASSWORD" --host=mariadb $MARIADB_DATABASE
      < environment/db/renfeid.sql --default-character-set=utf8
    - wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo
      -O /etc/yum.repos.d/epel-apache-maven.repo
    - yum -y install apache-maven
  script:
    - git clone https://cd-robot:$CD_ROBOT_TOKEN@github.com/renfei/config.git
    - cp ./config/renfeid/application-gitlab.yml ./src/main/resources/
    - mvn -P gitlab --batch-mode test --file pom.xml
  artifacts:
    expire_in: 1d
    when: on_success
    paths:
      - src/main/resources/ip2location/

test_job_gitlab:
  stage: test
  image: centos:centos7
  rules:
    - if: "$CI_SERVER_URL =~ /gitlab.com/"
  services:
    - mariadb:10.6.5
    - redis:6.0.1
    - name: "registry.gitlab.com/renfei/elasticsearch:7.16.2"
      alias: "elasticsearch"
      command: ["bin/elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node"]
  variables:
    MARIADB_DATABASE: renfeid
    MARIADB_ROOT_PASSWORD: root
  before_script:
    - yum install -y wget java-1.8.0-openjdk* which git
    - curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
    - rpm --import https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    - yum install -y MariaDB-server galera-4 MariaDB-client MariaDB-shared MariaDB-backup MariaDB-common
    - mariadb --user=root --password="$MARIADB_ROOT_PASSWORD" --host=mariadb $MARIADB_DATABASE
      < environment/db/renfeid.sql --default-character-set=utf8
    - wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo
      -O /etc/yum.repos.d/epel-apache-maven.repo
    - yum -y install apache-maven
  script:
    - git clone https://cd-robot:$CD_ROBOT_TOKEN@github.com/renfei/config.git
    - cp ./config/renfeid/application-gitlab.yml ./src/main/resources/
    - mvn -P gitlab --batch-mode test --file pom.xml
  artifacts:
    expire_in: 1d
    when: on_success
    paths:
      - src/main/resources/ip2location/

sast:
  stage: test
  artifacts:
    expire_in: 1d

include:
  - template: Security/SAST.gitlab-ci.yml
    artifacts:
      expire_in: 1d
  - template: Security/SAST-IaC.latest.gitlab-ci.yml
    artifacts:
      expire_in: 1d
  - template: Security/Dependency-Scanning.gitlab-ci.yml
    artifacts:
      expire_in: 1d
  - template: Security/Secret-Detection.gitlab-ci.yml
    artifacts:
      expire_in: 1d

release_jh:
  stage: release
  image: centos:centos7
  rules:
    - if: "$CI_COMMIT_TAG && $CI_SERVER_URL =~ /jihulab.com/"
  before_script:
    - yum install -y yum-utils
    - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - yum install docker-ce docker-ce-cli containerd.io
    - systemctl start docker
    - rm -rf config
    - git clone https://cd-robot:$CD_ROBOT_TOKEN@github.com/renfei/config.git
    - cp ./config/renfeid/application-gitlab.yml ./src/main/resources/
  script:
    - chmod +x ./environment/shell/buildDockerPushJiHu.sh
    - ./environment/shell/buildDockerPushJiHu.sh "$DOCKER_REGISTRY_PASSWORD"
  environment:
    name: production
    url: https://www.renfei.net/

release_gitlab:
  stage: release
  image: centos:centos7
  rules:
    - if: '$CI_COMMIT_TAG && $CI_SERVER_URL =~ /gitlab.com/'
  before_script:
    - yum install -y yum-utils
    - yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
    - yum install docker-ce docker-ce-cli containerd.io
    - systemctl start docker
    - rm -rf config
    - git clone https://cd-robot:$CD_ROBOT_TOKEN@github.com/renfei/config.git
    - cp ./config/renfeid/application-gitlab.yml ./src/main/resources/
  script:
    - chmod +x ./environment/shell/buildDockerPushGitLab.sh
    - ./environment/shell/buildDockerPushGitLab.sh "$DOCKER_REGISTRY_PASSWORD"
  environment:
    name: production
    url: https://www.renfei.net/