image: centos:centos7

stages:
  - initialize

initialize_environmen_jihu:
  stage: initialize
  script:
    - sed -e 's|^mirrorlist=|#mirrorlist=|g'
      -e 's|^#baseurl=http://mirror.centos.org|baseurl=https://mirrors.tuna.tsinghua.edu.cn|g'
      -i.bak /etc/yum.repos.d/CentOS-*.repo
    - yum makecache
    - yum install -y wget java-1.8.0-openjdk*
    - wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
    - yum install -y apache-maven
    - wget https://gitlab.cn/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.BIN.ZIP
    - wget https://gitlab.cn/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP
    - unzip IP2LOCATION-LITE-DB11.BIN.ZIP
    - unzip IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP
    - ls -l
    - echo $CI_SERVER_URL
#  rules:
#    - if: '$CI_SERVER_URL = '