image: centos:centos7

stages:
  - initialize
  - compile
  - test
  - package
  - release

cache:
  paths:
    - ".m2/repository/"

initialize:
  stage: initialize
  script:
    - yum install -y wget unzip
    - wget $CI_SERVER_URL/$CI_PROJECT_NAMESPACE/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.BIN.ZIP
    - wget $CI_SERVER_URL/$CI_PROJECT_NAMESPACE/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP
    - unzip -o IP2LOCATION-LITE-DB11.BIN.ZIP -d src/main/resources/ip2location/
    - unzip -o IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d src/main/resources/ip2location/
  artifacts:
    expire_in: 1d
    when: on_success
    paths:
      - src/main/resources/ip2location/

compile:
  stage: compile
  image: maven:3.8.4-openjdk-8
  script:
    - mvn --batch-mode compile
  artifacts:
    expire_in: 1d
    when: on_success
    paths:
      - src/main/resources/ip2location/

test:
  stage: test
  image: centos:centos7
  services:
    - mariadb:10.6.5
    - redis:6.0.1
    - name: "$CI_REGISTRY/$CI_PROJECT_NAMESPACE/elasticsearch:7.16.2"
      alias: "elasticsearch"
      command: [ "bin/elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node" ]
  variables:
    MARIADB_DATABASE: renfeid
    MARIADB_ROOT_PASSWORD: root
  before_script:
    - yum install -y wget java-1.8.0-openjdk* which git
    - curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
    - rpm --import https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    - yum install -y MariaDB-server galera-4 MariaDB-client MariaDB-shared MariaDB-backup MariaDB-common
    - mariadb --user=root --password="$MARIADB_ROOT_PASSWORD" --host=mariadb $MARIADB_DATABASE
      < environment/db/renfeid.sql --default-character-set=utf8
  script:
    - git clone https://cd-robot:$CD_ROBOT_TOKEN@github.com/renfei/config.git
    - cp ./config/renfeid/application-gitlab.yml ./src/main/resources/
    - ./mvnw test -P gitlab
  artifacts:
    expire_in: 1d
    when: on_success
    paths:
      - src/main/resources/ip2location/

package:
  stage: package
  image: centos:centos7
  rules:
    - if: $CI_COMMIT_TAG
  before_script:
    - yum install -y java-1.8.0-openjdk* which git
  script:
    - rm -rf config
    - git clone https://cd-robot:$CD_ROBOT_TOKEN@github.com/renfei/config.git
    - cp ./config/renfeid/application-prod.yml ./src/main/resources/
    - ./mvnw clean package -Dmaven.test.skip=true -P prod
  artifacts:
    expire_in: 1 seconds
    when: on_success
    paths:
      - /target/
      - /src/main/resources/

release:
  stage: release
  image: docker:latest
  rules:
    - if: $CI_COMMIT_TAG
  services:
    - docker:dind
  before_script:
    - dicker info
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker login --username=$CI_REGISTRY_USER --password=$CI_REGISTRY_PASSWORD $CI_REGISTRY_IMAGE
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  dependencies:
    - package
  environment:
    name: production
    url: https://www.renfei.net/