stages:
  - test
  - build
  - deploy

test_job:
  stage: test
  script:
    - echo 'TODO....'

nuxt_build_job:
  stage: build
  script:
    - echo 'TODO....'

maven_build_job:
  stage: build
  script:
    - echo 'TODO....'

nodejs_docker_job:
  stage: deploy
  script:
    - echo 'TODO....'

java_docker_job:
  stage: deploy
  script:
    - echo 'TODO....'

sast:
  stage: test
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: License-Scanning.gitlab-ci.yml