image: centos:centos7

stages:
  - initialize
  - compile
  - test

cache:
  paths:
    - .m2/repository/

initialize_environmen_jihu:
  stage: initialize
  script:
    - yum install -y wget unzip
    - wget https://gitlab.cn/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.BIN.ZIP
    - wget https://gitlab.cn/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP
    - unzip -o IP2LOCATION-LITE-DB11.BIN.ZIP -d src/main/resources/ip2location/
    - unzip -o IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d src/main/resources/ip2location/
  artifacts:
    when: on_success
    paths:
      - src/main/resources/ip2location/
  rules:
    - if: $CI_SERVER_URL =~ /gitlab.cn/

initialize_environmen_gitlab:
  stage: initialize
  script:
    - yum install -y wget unzip
    - wget https://gitlab.com/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.BIN.ZIP
    - wget https://gitlab.com/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP
    - unzip -o IP2LOCATION-LITE-DB11.BIN.ZIP -d src/main/resources/ip2location/
    - unzip -o IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d src/main/resources/ip2location/
  artifacts:
    when: on_success
    paths:
      - src/main/resources/ip2location/
  rules:
    - if: $CI_SERVER_URL =~ /gitlab.com/

compile:
  stage: compile
  image: maven:latest
  script:
    - mvn --batch-mode compile

test_job:
  stage: test
  image: centos:centos7
  services:
    - mysql:5.7
    - redis:6.0.1
  variables:
    MYSQL_DATABASE: renfeid
    MYSQL_ROOT_PASSWORD: root
  before_script:
    - yum install mysql-client maven mysql
    - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql $MYSQL_DATABASE < environment/db/renfeid.sql --ssl-mode=REQUIRED --default-character-set=utf8
  script:
    - mvn -P gitlab --batch-mode test jacoco:report --file pom.xml
    - bash <(curl -s https://codecov.io/bash)
    - sed -i.bak 's/yourcoverallsprojectrepositorytoken/$COVERALLS_TOKEN/g' pom.xml
    - mvn coveralls:report
