image: centos:centos7

stages:
  - initialize
  - compile
  - test
  - deploy

cache:
  paths:
    - ".m2/repository/"

initialize_environmen_jihu:
  stage: initialize
  script:
    - yum install -y wget unzip
    - wget https://jihulab.com/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.BIN.ZIP
    - wget https://jihulab.com/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP
    - unzip -o IP2LOCATION-LITE-DB11.BIN.ZIP -d src/main/resources/ip2location/
    - unzip -o IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d src/main/resources/ip2location/
  artifacts:
    expire_in: 1d
    when: on_success
    paths:
      - src/main/resources/ip2location/
  rules:
    - if: "$CI_SERVER_URL =~ /jihulab.com/"

initialize_environmen_gitlab:
  stage: initialize
  script:
    - yum install -y wget unzip
    - wget https://gitlab.com/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.BIN.ZIP
    - wget https://gitlab.com/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP
    - unzip -o IP2LOCATION-LITE-DB11.BIN.ZIP -d src/main/resources/ip2location/
    - unzip -o IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d src/main/resources/ip2location/
  artifacts:
    expire_in: 1d
    when: on_success
    paths:
      - src/main/resources/ip2location/
  rules:
    - if: "$CI_SERVER_URL =~ /gitlab.com/"

compile:
  stage: compile
  image: maven:3.8.4-openjdk-8
  script:
    - mvn --batch-mode compile

test_job_jh:
  stage: test
  image: centos:centos7
  services:
    - mariadb:10.6.5
    - redis:6.0.1
    - name: "registry.jihulab.com/renfei/elasticsearch:7.16.2"
      alias: "elasticsearch"
      command: [ "bin/elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node" ]
  variables:
    MARIADB_DATABASE: renfeid
    MARIADB_ROOT_PASSWORD: root
  before_script:
    - yum install -y wget java-1.8.0-openjdk* which git
    - curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
    - rpm --import https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    - yum install -y MariaDB-server galera-4 MariaDB-client MariaDB-shared MariaDB-backup MariaDB-common
    - mariadb --user=root --password="$MARIADB_ROOT_PASSWORD" --host=mariadb $MARIADB_DATABASE
      < environment/db/renfeid.sql --default-character-set=utf8
    - wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo
      -O /etc/yum.repos.d/epel-apache-maven.repo
    - yum -y install apache-maven
  script:
    - git clone https://cd-robot:$CD_ROBOT_TOKEN@github.com/renfei/config.git
    - cp ./config/renfeid/application-gitlab.yml ./src/main/resources/
    - mvn -P gitlab --batch-mode test --file pom.xml
  rules:
    - if: "$CI_SERVER_URL =~ /jihulab.com/"

test_job_gitlab:
  stage: test
  image: centos:centos7
  services:
    - mariadb:10.6.5
    - redis:6.0.1
    - name: "registry.gitlab.com/renfei/elasticsearch:7.16.2"
      alias: "elasticsearch"
      command: ["bin/elasticsearch", "-Expack.security.enabled=false", "-Ediscovery.type=single-node"]
  variables:
    MARIADB_DATABASE: renfeid
    MARIADB_ROOT_PASSWORD: root
  before_script:
    - yum install -y wget java-1.8.0-openjdk* which git
    - curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | bash
    - rpm --import https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
    - yum install -y MariaDB-server galera-4 MariaDB-client MariaDB-shared MariaDB-backup MariaDB-common
    - mariadb --user=root --password="$MARIADB_ROOT_PASSWORD" --host=mariadb $MARIADB_DATABASE
      < environment/db/renfeid.sql --default-character-set=utf8
    - wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo
      -O /etc/yum.repos.d/epel-apache-maven.repo
    - yum -y install apache-maven
  script:
    - git clone https://cd-robot:$CD_ROBOT_TOKEN@github.com/renfei/config.git
    - cp ./config/renfeid/application-gitlab.yml ./src/main/resources/
    - mvn -P gitlab --batch-mode test --file pom.xml
  rules:
    - if: "$CI_SERVER_URL =~ /gitlab.com/"

sast:
  stage: test

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/SAST-IaC.latest.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  environment:
    name: production
    url: https://www.renfei.net/
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#      when: manual