image: centos:centos7

stages:
  - initialize
  - build
  - connect
  - test

variables:
  MAVEN_CLI_OPTS: "--batch-mode"
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MYSQL_DATABASE: renfeid
  MYSQL_ROOT_PASSWORD: root

cache:
  paths:
    - .m2/repository/

initialize_environmen_jihu:
  stage: initialize
  script:
    - yum install -y wget unzip
    - wget https://gitlab.cn/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.BIN.ZIP
    - wget https://gitlab.cn/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP
    - unzip -o IP2LOCATION-LITE-DB11.BIN.ZIP -d src/main/resources/ip2location/
    - unzip -o IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d src/main/resources/ip2location/
  artifacts:
    paths:
      - src/main/resources/ip2location/
  rules:
    - if: $CI_SERVER_URL =~ /gitlab.cn/

initialize_environmen_gitlab:
  stage: initialize
  script:
    - yum install -y wget unzip
    - wget https://gitlab.com/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.BIN.ZIP
    - wget https://gitlab.com/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP
    - unzip -o IP2LOCATION-LITE-DB11.BIN.ZIP -d src/main/resources/ip2location/
    - unzip -o IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d src/main/resources/ip2location/
  artifacts:
    paths:
      - src/main/resources/ip2location/
  rules:
    - if: $CI_SERVER_URL =~ /gitlab.com/

build:
  stage: build
  image: maven:latest
  script:
    - mvn $MAVEN_CLI_OPTS clean compile

connect:
  stage: connect
  image: mysql:5.7
  script:
    - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql -e "CREATE DATABASE $MYSQL_DATABASE"
    - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql $MYSQL_DATABASE < environment/db/renfeid.sql --ssl-mode=REQUIRED --default-character-set=utf8

test_job:
  stage: test
  image: maven:latest
  services:
    - mysql:5.7
    - redis:6.0.1
  script:
    - mvn -P gitlab $MAVEN_CLI_OPTS test jacoco:report --file pom.xml
    - bash <(curl -s https://codecov.io/bash)
    - sed -i.bak 's/yourcoverallsprojectrepositorytoken/${{ secrets.COVERALLS_TOKEN }}/g' pom.xml
    - mvn coveralls:report