image: centos:centos7

stages:
  - initialize
  - test

services:
  - mysql:5.7
  - redis:6.0.1

variables:
  MYSQL_DATABASE: renfeid
  MYSQL_ROOT_PASSWORD: root

connect:
  stage: test
  image: mysql:5.7
  script:
    - echo "SELECT 'OK';"
    - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE" --ssl-mode=REQUIRED

initialize_environmen_jihu:
  stage: initialize
  script:
    - sed -e 's|^mirrorlist=|#mirrorlist=|g'
      -e 's|^#baseurl=http://mirror.centos.org|baseurl=https://mirrors.tuna.tsinghua.edu.cn|g'
      -i.bak /etc/yum.repos.d/CentOS-*.repo
    - yum makecache
    - yum install -y wget java-1.8.0-openjdk* unzip
    - wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
    - yum install -y apache-maven
    - wget https://gitlab.cn/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.BIN.ZIP
    - wget https://gitlab.cn/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP
    - unzip -o IP2LOCATION-LITE-DB11.BIN.ZIP -d src/main/resources/ip2location/
    - unzip -o IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d src/main/resources/ip2location/
  rules:
    - if: $CI_SERVER_URL =~ /gitlab.cn/

initialize_environmen_gitlab:
  stage: initialize
  script:
    - yum install -y wget java-1.8.0-openjdk* unzip
    - wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
    - yum install -y apache-maven
    - wget https://gitlab.com/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.BIN.ZIP
    - wget https://gitlab.com/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP
    - unzip -o IP2LOCATION-LITE-DB11.BIN.ZIP  -d src/main/resources/ip2location/
    - unzip -o IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d src/main/resources/ip2location/
  rules:
    - if: $CI_SERVER_URL =~ /gitlab.com/

test_job:
  stage: test
  before_script:
    - mysql --user=root --password=\"$MYSQL_ROOT_PASSWORD\" --host=mysql < environment/db/renfeid.sql
  script:
    - mvn -P gitlab clean test jacoco:report --file pom.xml
    - bash <(curl -s https://codecov.io/bash)
    - sed -i.bak 's/yourcoverallsprojectrepositorytoken/${{ secrets.COVERALLS_TOKEN }}/g' pom.xml
    - mvn coveralls:report