image: centos:centos7

stages:
  - initialize
  - test

services:
  - mysql:5.7
  - redis:6.0.1

variables:
  MYSQL_DATABASE: renfeid
  MYSQL_ROOT_PASSWORD: root

connect:
  stage: test
  image: mysql:5.7
  script:
    - echo "SELECT 'OK';"
    - mysql --user=root --password="$MYSQL_ROOT_PASSWORD" --host=mysql "$MYSQL_DATABASE" --ssl-mode=REQUIRED

initialize_environmen:
  stage: initialize
  script:
    - yum install -y wget unzip
    - wget https://gitlab.cn/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.BIN.ZIP
    - wget https://gitlab.cn/renfei/ip2location/-/raw/master/IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP
    - unzip -o IP2LOCATION-LITE-DB11.BIN.ZIP -d src/main/resources/ip2location/
    - unzip -o IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d src/main/resources/ip2location/

test_job:
  stage: test
  before_script:
    - yum install -y wget
    - wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
    - rpm -ivh https://repo.mysql.com//mysql57-community-release-el7-11.noarch.rpm
    - yum install -y java-1.8.0-openjdk* apache-maven mysql-community-client.x86_64
    - mysql --user=root --password=\"$MYSQL_ROOT_PASSWORD\" --host=mysql < environment/db/renfeid.sql
  script:
    - mvn -P gitlab clean test jacoco:report --file pom.xml
    - bash <(curl -s https://codecov.io/bash)
    - sed -i.bak 's/yourcoverallsprojectrepositorytoken/${{ secrets.COVERALLS_TOKEN }}/g' pom.xml
    - mvn coveralls:report