####################################
#     开发环境配置文件 RENFEI.NET
#      --=== 配置说明 ===--
# * local.renfei.net 默认解析为本机地址
#   如果在特殊环境中修改 hosts 文件即可
####################################
server:
  port: 9595

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mariadb://local.renfei.net:3306/renfeid?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: admin
    discuz:
      url: jdbc:mariadb://local.renfei.net:3306/discuz?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&useSSL=false
      driver-class-name: org.mariadb.jdbc.Driver
      username: root
      password: root
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: WEB-INF/**
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
#    password: password
    timeout: 3000ms # 连接超时时间
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数
        max-idle: 8 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
  mail:
    host: smtp.exmail.qq.com
    port: 465
    username: no-reply@renfei.net
    password: <password>
    protocol: smtp
    default-encoding: UTF-8
    reply-to: i@renfei.net
    properties:
      mail.smtp.localhost: renfei.net
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
    jndi-name: mail/Session
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
  elasticsearch:
    uris: http://local.renfei.net:9200
# 自定义配置
system:
  active: dev
  version: "@project.version@"
  buildTime: "@buildtimestamp@"
  baseDomainName: .renfei.net
  siteDomainName: http://local.renfei.net:9595
  staticDomain: https://cdn.renfei.net
  enableRedis: true
  authMode: SESSION
  globalAesKey: globalAesKey
  leafKey: leaf-segment-global
  ownerUserName: renfei
  siteName: 任霏的博客
  defaultCacheSeconds: 7200
  showFriendlyLink: true
  totpSecret: dH6xS3rG7eS6oS3bK9aN4iW8bR2vU9nV
  footerSmallMenu:
    - 冀公网安备 13070902000275号@http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=13070902000275
    - 冀ICP备12003293号-9@https://beian.miit.gov.cn/
    - 任霏@https://www.renfei.net/
    - 使用条款@https://www.renfei.net/page/2
    - 隐私与 Cookie@https://www.renfei.net/page/1
    - Status@https://status.renfei.net/
  pageHead:
    author: 任霏,i@renfei.net
    copyright: CopyRight RENFEI.NET, All Rights Reserved.
    dnsPrefetch:
      - //www.renfei.net
      - //cdn.renfei.net
      - //cdn.jsdelivr.net
      - //hm.baidu.com
      - //www.googletagmanager.com
      - //www.google-analytics.com
      - //www.recaptcha.net
    fbAppId: 205704373959112
    fbPages: 108842630700746
    favicon: https://cdn.renfei.net/favicon.ico
    appleTouchIcon: https://cdn.renfei.net/Logo/logo_192.png
    css:
      - https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css
      - https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.1/css/all.min.css
      - /css/bs4.pop.css
      - /css/style.css?ver=${system.version}
  pageFooter:
    jss:
      - https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
      - https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js
      - https://cdn.renfei.net/thunder/js/popper.min.js
      - https://cdn.renfei.net/thunder/js/clipboard.min.js
      - /js/bs4.pop.js
      - /js/main.js?ver=${system.version}
      - https://www.recaptcha.net/recaptcha/api.js?render=${system.google.reCAPTCHA.clientKey}
      - https://www.googletagmanager.com/gtag/js?id=${system.google.analytics}
      - https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js
  # https://github.com/renfei/ip2location/releases
  ip2LocationBinFile: classpath:/ip2location/IP2LOCATION-LITE-DB11.BIN
  ip2LocationBinFileV6: classpath:/ip2location/IP2LOCATION-LITE-DB11.IPV6.BIN
#  ip2LocationBinFile: /opt/renfeid/ip2location/IP2LOCATION-LITE-DB11.BIN
#  ip2LocationBinFileV6: /opt/renfeid/ip2location/IP2LOCATION-LITE-DB11.IPV6.BIN
  leaf:
    segment:
      enable: true
    snowflake:
      enable: false
      zk:
        address: xxx
      port: 1111
  threadPool:
    corePoolSize: 10
    maxPoolSize: 20
    keepAliveSeconds: 300
    queueCapacity: 100
  aliyun:
    accessKeyId: <accessKeyId>
    accessKeySecret: <accessKeySecret>
    oss:
      endpoint: http://oss-cn-hangzhou.aliyuncs.com
      bucketName: renfei
      downloadBucketName: down-renfei
      downloadHost: https://download.renfei.net
    green:
      regionId: cn-beijing
    sms:
      regionId: cn-hangzhou
      signName: 任霏博客
      templateCode: SMS_205876298
  weChat:
    appId: wx0aeac235b86963c1
    appSecret: a2443ee4b6d60e202287c3a27a89d712
    token: tttt123sdg
    encodingAESKey: <encodingAESKey>
  baidu:
    tongji: 1
  google:
    analytics: 1
    ads: 1
    reCAPTCHA:
      clientKey: 6Le3eAsaAAAAAJ5P-m7D9tCEZbu2WLpKRoS6_Lw5
      serverKey: 6Le3eAsaAAAAAMUFrytHPgKkMlLeWR7s1YAFrOMW
  jwt:
    secret: zL4pC7mP4vH4nY2cK1kE6lC3bJ0yC5wI4kB0kZ2wK4tW3nQ9vP1hO6vZ5jA7wP7ulN6vY3mQ7uI5wU5sE6yP0hP6pK0tF5tT1oO0nO2mL4nO8uP3kJ3rV3iJ4aD5iB5h
    issuer: RENFEI.NET
    expiration: 28800000
  uCenter:
    api: https://bbs.renfei.net/uc_server
    key: <key>
    appId: 3
    connect:
sentry:
  dsn: https://8843a97fdea6415bae0f696f3749eaf6@o1071939.ingest.sentry.io/6069834
  environment: development
  release: "@project.version@"
  traces-sample-rate: 0.3