server:
  port: 8081

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://10.10.1.2:3306/renfeid?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 3
      min-idle: 3
      max-active: 10
      max-wait: 60000
      stat-view-servlet:
        login-username: admin
        login-password: admin
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  elasticsearch:
    rest:
      uris: http://localhost:9200
  redis:
    ## Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
  mail:
    host: <host>
    port: 465
    username: no-reply@renfei.net
    password: <password>
    protocol: smtp
    default-encoding: UTF-8
    reply-to: i@renfei.net
    properties:
      mail.smtp.localhost: renfei.net
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.socketFactory.port: 465
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
    jndi-name: mail/Session
  freemarker:
    cache: false
    settings:
      template_update_delay: 0
# 自定义配置
system:
  active: dev
  version: @project.version@
  buildTime: @buildtimestamp@
  globalAesKey: globalAesKey
  leafKey: leaf-segment-global
  ownerUserName: renfei
  siteName: 任霏的博客
  # git clone https://gitlab.com/renfei/ip2location.git
  ip2LocationBinFile: /opt/renfeid/ip2location/IP2LOCATION-LITE-DB11.BIN
  ip2LocationBinFileV6: /opt/renfeid/ip2location/IP2LOCATION-LITE-DB11.IPV6.BIN
  leaf:
    segment:
      enable: true
    snowflake:
      enable: false
      zk:
        address: xxx
      port: 1111
sentry:
  dsn: https://8843a97fdea6415bae0f696f3749eaf6@o1071939.ingest.sentry.io/6069834
  environment: development
  release: @project.version@
  traces-sample-rate: 0.3