spring:
  profiles:
    active: @activatedProperties@
  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 64MB
  session:
    store-type: redis
    redis:
      namespace: spring:session
  datasource:
    druid:
    # 由于在 net.renfei.config.PrimaryDataSourceConfig 手动注册数据源下方配置失效
    # 下方 Druid 配置在 net.renfei.config.PrimaryDataSourceConfig
    # stat-view-servlet配置在 net.renfei.servlet.ServletRegistration.statViewServlet
    # 由于此处的配置几乎不怎么修改，所以直接在代码里硬编码了，懒得写入配置文件中
    #
    #  initial-size: 5
    #  min-idle: 5
    #  max-active: 20
    #  max-wait: 60000
    #  test-on-borrow: false
    #  test-while-idle: true
    #  test-on-return: false
    #  validation-query: select 1
    #  time-between-eviction-runs-millis: 60000
    #  min-evictable-idle-time-millis: 300000
    #  pool-prepared-statements: true
    #  max-pool-prepared-statement-per-connection-size: 20
    #  filters: stat,wall
    #  use-global-data-source-stat: true
    #  connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    #  stat-view-servlet:
    #    enabled: true
    #    reset-enable: false
    #    url-pattern: /druid/*
    #  web-stat-filter:
    #    url-pattern: /*
    #    exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
    #    enabled: true
  freemarker:
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
  quartz:
    job-store-type: JDBC
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: false
    path: /swagger-ui.html
  show-actuator: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    ## 打印SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
