server:
  port: 9595

spring:
  profiles:
    active: @activatedProperties@

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    ## 打印SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql