name: PushCI

on: [ push ]

jobs:
  test:
    name: building
    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    services:
      mariadb:
        image: mariadb:10.6.5
        ports:
          - 3306:3306
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
          MARIADB_DATABASE: renfeid
          MARIADB_ROOT_PASSWORD: root
        options:
          --health-cmd="mariadb-admin ping"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=3
      redis:
        image: redis:6.0.1
        ports:
          - 6379:6379
      elasticsearch:
        image: ghcr.io/renfei/elasticsearch:7.17.0
        ports:
          - 9200:9200
          - 9300:9300
        env:
          discovery.type: single-node

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Verify MariaDB Connection and Load Data
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done

      - name: Loading Database
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: mysql -h 127.0.0.1 -P $PORT -uroot -proot --default-character-set=utf8 renfeid < environment/db/renfeid.sql

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Download IP2Location BIN File
        run: |
          wget -P ./src/main/resources/ip2location https://github.com/renfei/ip2location/releases/download/2022.01.02/IP2LOCATION-LITE-DB11.BIN
          wget -P ./src/main/resources/ip2location https://github.com/renfei/ip2location/releases/download/2022.01.02/IP2LOCATION-LITE-DB11.IPV6.BIN

      - name: Pull Config File
        run: |
          git clone https://cd-robot:${{ secrets.CD_ROBOT_TOKEN }}@github.com/renfei/config.git
          cp ./config/renfeid/application-ci.yml ./src/main/resources/

      - name: Tests
        run: mvn clean test jacoco:report -P ci --file pom.xml

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)

      - name: Upload coverage to Coveralls
        run: |
          sed -i.bak 's/yourcoverallsprojectrepositorytoken/${{ secrets.COVERALLS_TOKEN }}/g' pom.xml
          mvn -P ci coveralls:report

  security:
    runs-on: ubuntu-latest

    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - uses: actions/checkout@master

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif