name: PushCI

on: [ push ]

jobs:
  build:
    name: building
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        ports:
          - 3306:3306
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: renfeid
          MYSQL_ROOT_PASSWORD: root
        options:
          --health-cmd="mysqladmin ping"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=3
      redis:
        image: redis:6.0.1
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Verify MariaDB Connection and Load Data
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done

      - name: Loading Database
        env:
          PORT: ${{ job.services.mysql.ports[3306] }}
        run: mysql -h 127.0.0.1 -P $PORT -uroot -proot --default-character-set=utf8 renfeid < environment/db/renfeid.sql

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Download IP2Location BIN File
        run: |
          wget -P ./src/main/resources/ip2location https://github.com/renfei/ip2location/releases/download/2021.12.05/IP2LOCATION-LITE-DB11.BIN
          wget -P ./src/main/resources/ip2location https://github.com/renfei/ip2location/releases/download/2021.12.05/IP2LOCATION-LITE-DB11.IPV6.BIN

      - name: Tests
        run: mvn clean test jacoco:report --file pom.xml

      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)

      - name: Upload coverage to Coveralls
        run: |
          sed -i.bak 's/yourcoverallsprojectrepositorytoken/${{ secrets.COVERALLS_TOKEN }}/g' pom.xml
          mvn coveralls:report

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=renfei_renfeid
