name: Release

on:
  release:
    types: [ published ]

jobs:
  build:
    name: building
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.6.5
        ports:
          - 3306:3306
        env:
          MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: yes
          MARIADB_DATABASE: renfeid
          MARIADB_ROOT_PASSWORD: root
        options:
          --health-cmd="mariadb-admin ping"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=3
      redis:
        image: redis:6.0.1
        ports:
          - 6379:6379
      elasticsearch:
        image: ghcr.io/renfei/elasticsearch:7.16.2
        ports:
          - 9200:9200
          - 9300:9300

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Verify MariaDB Connection and Load Data
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done

      - name: Loading Database
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: mysql -h 127.0.0.1 -P $PORT -uroot -proot --default-character-set=utf8 renfeid < environment/db/renfeid.sql

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Pull Production Config(application-prod.yml)
        run: |
          git clone https://cd-robot:${{ secrets.cd_robot_token }}@github.com/renfei/config.git && \
          cp ./config/renfeid/application-prod.yml ./src/main/resources/

      # Dockerfile 里会复制 ip2location 中的 BIN 文件
      - name: Pull IP2Location Database BinFile
        run: |
          mkdir ip2location
          wget -P ./ip2location https://github.com/renfei/ip2location/releases/download/2021.12.05/IP2LOCATION-LITE-DB11.BIN
          wget -P ./ip2location https://github.com/renfei/ip2location/releases/download/2021.12.05/IP2LOCATION-LITE-DB11.IPV6.BIN
          unzip -o ./ip2location/IP2LOCATION-LITE-DB11.BIN.ZIP -d ./src/main/resources/ip2location/
          unzip -o ./ip2location/IP2LOCATION-LITE-DB11.IPV6.BIN.ZIP -d ./src/main/resources/ip2location/

      - name: Build And Push Docker Image
        run: |
          chmod +x ./environment/shell/buildDockerPushGitHub.sh
          ./environment/shell/buildDockerPushGitHub.sh "${{ secrets.docker_registry_password }}"

      - name: Sentry Release
        uses: getsentry/action-release@v1.1.6
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: renfei
          SENTRY_PROJECT: renfeid
        with:
          environment: production
          version: ${{ github.event.release.tag_name }}